### PR TITLE
Revert "PanFrames: always keep mapped"

### PR DESCRIPTION
**Pull request by codedmart**
PR reverting per conversation with @ThomasAdam on irc. This broke the auto_hide function I use for my top bar in my config.

This reverts commit 29f00243542bd23aa28c6f51d83db4483e05a6b0.

* **What does this PR do?**

* **Screenshots (if applicable)**

* **PR acceptance criteria** (reminder only, please delete once read)

  - Your commit message(s) are descriptive.  See:

    https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

  - [https://raw.githubusercontent.com/fvwmorg/fvwm3/master/doc/README]Documentation updated (where appropriate)

  - Style guide followed (try and match the surrounding code where possible)

  - All tests are passing:  although this is automatic, Codacy will often
    highlight additional considerations which will need to be addressed before
    the PR can be merged.

* **Issue number(s)**

If this PR addresses any issues, please ensure the appropriate commit
message(s) contains:

```
Fixes #XXX
```

at the end of your commit message, where `XXX` should be replaced with the
relevant issue number.

If there is more than one issue fixed then use:

```
Fixes #XXX, fixes #YYY, fixes #ZZZ
```

### CODE REVIEW

**Comment by phileimer** [comment]
Hi @codedmart 
You seem to have the same trouble I reported in #381, following this commit 29f00243542bd23aa28c6f51d83db4483e05a6b0.
May be the EdgeThickness workaround I describe there could work for you.

**Comment by ThomasAdam** [comment]
Hi @codedmart 

Please take a look at `ta/panframe-improvements` and let me know if any of the issues you raised here are resolved or not.

**Comment by ThomasAdam** [comment]
I'll close this for now, as the changes on `ta/panframe-improvements` cover this.  Please comment on #381 for any further panframe problems.

**Comment by codedmart** [comment]
@ThomasAdam I can test that branch on Monday. Thanks!

**Pull request closed without merging**
