### PR TITLE
Make xkbcommon required in meson. 

### PR DESCRIPTION
**Pull request by somiaj**
Noticed there were a few missing optional dependencies.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
@somiaj 

Sure. But, I would argue that xkbcommon should now be a core dependency. 

Just for meson. Although that's already implied with xfixes being introduced.

**Comment by ThomasAdam** [comment]
@somiaj 

Re xkbcommon, wing were also need to change meson.build?

**Comment by somiaj** [comment]
Ahh I thought you already updated that. Shouldn't we also remove the fallback code as well (though I guess this will only affect meson).

**Comment by ThomasAdam** [comment]
@somiaj 

I'm not updating. Just pointing this out. I guess this is delegation by subterfuge. 🙂

I don't think we need to worry about fallback code. Just meson.

**Comment by Kangie** [comment]
LGTM

**Pull request merged**
