### PR TITLE
fix crash in the menu script; escape menuitem text

### LINKED ISSUE #177: fvwm-menu-desktop only produces half the xdg-menu
From roughly the penultimate (?) update of master branch on, my XDG-menu is broken. The script only produces up to Graphics, and from Internet onwards, the items remain empty. Here's the end of the output, beginning with the final working entry "Grafik":

```
DestroyMenu "Grafik"
AddToMenu "Grafik" "Grafik" Title
+ "E-book viewer%/home/peter/.fvwm/icons/24x24-calibre-viewer.png%" Exec exec ebook-viewer --detach 
+ "Flameshot%/home/peter/.fvwm/icons/24x24-flameshot.png%" Exec exec flameshot
+ "GNU Image Manipulation Program%/usr/share/icons/hicolor/24x24/apps/gimp.png%" Exec exec gimp-2.10 
+ "LRF viewer%/home/peter/.fvwm/icons/24x24-calibre-viewer.png%" Exec exec lrfviewer 
+ "LibreOffice Draw%/usr/share/icons/hicolor/24x24/apps/libreoffice-draw.png%" Exec exec libreoffice --draw 
%s icon or default icon not found!
+ "XDvi" Exec exec xdvi 
Traceback (most recent call last):
  File "/usr/local/bin/fvwm-menu-desktop", line 877, in <module>
    main()
  File "/usr/local/bin/fvwm-menu-desktop", line 461, in main
    parsemenus(menulist, desktop, desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 717, in parsemenus
    parsemenu(xdg.Menu.parse(menulist[0]), top, '', desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 822, in parsemenu
    parsemenu(entry, '', '', desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 801, in parsemenu
    printmenu(desktop.getName(), desktop.getIcon(), "Exec exec " + execProgram)
  File "/usr/local/bin/fvwm-menu-desktop", line 706, in printmenu
    iconfile = geticonfile(icon) or getdefaulticonfile(command) or icon
  File "/usr/local/bin/fvwm-menu-desktop", line 693, in geticonfile
    if st.check_size():
  File "/usr/local/bin/fvwm-menu-desktop", line 129, in check_size
    return self._do_check()
  File "/usr/local/bin/fvwm-menu-desktop", line 160, in _do_check
    with PIL.Image.open(self.filename) as f:
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2920, in open
    im = _open_core(fp, filename, prefix)
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2902, in _open_core
    im = factory(fp, filename)
  File "/usr/lib/python3.8/site-packages/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/usr/lib/python3.8/site-packages/PIL/XpmImagePlugin.py", line 60, in _open
    raise ValueError("cannot read this XPM file")
ValueError: cannot read this XPM file
```

### PR DESCRIPTION
**Pull request by mikeandmore**
attempt to fix #177 as well.

### CODE REVIEW

**Comment by mikeandmore** [comment]
That's just removing the trailing whitespace.

**Comment by ThomasAdam** [comment]
Yes, I'm saying it shouldn't be part of this commit.

If subsequent changes happen in those areas, there'll be conflicts.

Please regenerate your patch to just the code changes without these whitespace changes.

**Comment by mikeandmore** [comment]
@ThomasAdam I just did a force push. Does that look better?

**Comment by ThomasAdam** [comment]
Hi @mikeandmore,

That's looking good.  Perfect.  Hopefully you can appreciate why I asked for that change.  That's gone from an ~80 line change, down to ~15 lines, which shows just the code change.

Will merge.

**Comment by mikeandmore** [comment]
Thanks, but wait a second. I think I forgot to catch the exception when there's a failure.

**Pull request merged**
